import type { PublicContentData } from "@/types/public-content";

/** Fallback saat API belum tersedia */
export const DEFAULT_PUBLIC_CONTENT: PublicContentData = {
  site: {
    name: "FreshFold",
    tagline: "Laundry modern dengan antar jemput & tracking real-time",
    phone: "6281234567890",
    email: "hello@freshfold.id",
    address: "Jl. Raya Sudirman No. 45, Jakarta Selatan",
    hours: "Senin – Minggu, 07.00 – 21.00 WIB",
    whatsappMessage: "Halo FreshFold, saya ingin bertanya tentang layanan laundry.",
  },
  hero: {
    headline: "Laundry premium, sepraktis aplikasi on-demand",
    headlineHighlight: "sepraktis aplikasi on-demand",
    subheadline:
      "FreshFold menggabungkan antar jemput, tracking realtime, dan pembayaran cashless — pengalaman modern tanpa antre di outlet.",
    badges: ["Express 24 Jam", "Pickup & Delivery", "1000+ Pelanggan"],
    socialProof: "2.500+ pelanggan aktif bulan ini",
    images: {
      main: "https://images.unsplash.com/photo-1582735680399-3e889b9dd275?w=800&q=80",
      courier: "https://images.unsplash.com/photo-1600880292203-757bb62b3344?w=400&q=80",
      customer: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
      facility: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&q=80",
      background: "",
    },
  },
  promoStrip: {
    enabled: true,
    title: "Promo Member Baru:",
    description: "diskon 25% + gratis ongkir 3x",
    code: "FRESH25",
    linkLabel: "Lihat paket",
    linkHash: "harga",
  },
  stats: [
    { key: "washed", label: "Pakaian dicuci", value: 10000, suffix: "+", icon: "shirt" },
    { key: "customers", label: "Pelanggan aktif", value: 2500, suffix: "+", icon: "users" },
    { key: "satisfaction", label: "Customer puas", value: 98, suffix: "%", icon: "heart" },
    { key: "support", label: "Support", value: 24, suffix: "/7", icon: "headphones" },
  ],
  services: [
    {
      id: "reguler",
      name: "Cuci Reguler",
      description: "Cuci + setrika standar untuk kebutuhan harian keluarga.",
      priceLabel: "Rp 9.000/kg",
      estimate: "2–3 hari",
      icon: "shirt",
    },
    {
      id: "express",
      name: "Express",
      description: "Prioritas proses cepat — selesai dalam 6–12 jam.",
      priceLabel: "Rp 14.000/kg",
      estimate: "6–12 jam",
      icon: "zap",
    },
    {
      id: "dry-clean",
      name: "Dry Cleaning",
      description: "Perawatan khusus jas, gaun, dan bahan premium.",
      priceLabel: "Rp 35.000/item",
      estimate: "3–4 hari",
      icon: "wind",
    },
    {
      id: "setrika",
      name: "Setrika Saja",
      description: "Pakaian sudah bersih? Kami rapikan dengan setrika profesional.",
      priceLabel: "Rp 5.000/kg",
      estimate: "1 hari",
      icon: "layers",
    },
    {
      id: "sepatu",
      name: "Laundry Sepatu",
      description: "Deep clean sneaker & kasual, wangi dan higienis.",
      priceLabel: "Rp 35.000/pasang",
      estimate: "2–4 hari",
      icon: "footprints",
    },
    {
      id: "karpet",
      name: "Laundry Karpet",
      description: "Cuci karpet rumah & kantor, berbagai ukuran.",
      priceLabel: "Rp 25.000/m²",
      estimate: "3–5 hari",
      icon: "bed",
    },
  ],
  pricingTiers: [
    {
      id: "reguler",
      name: "Reguler",
      description: "Cuci standar untuk kebutuhan harian",
      priceKg: 9000,
      priceItem: 15000,
      features: ["Cuci + setrika", "Estimasi 2–3 hari", "Pickup gratis 3 km"],
      highlight: false,
    },
    {
      id: "express",
      name: "Express",
      description: "Paling populer untuk profesional sibuk",
      priceKg: 14000,
      priceItem: 22000,
      features: ["Prioritas antrian", "Selesai 6–12 jam", "Notifikasi realtime"],
      highlight: true,
    },
    {
      id: "premium",
      name: "Premium",
      description: "Perawatan khusus bahan premium",
      priceKg: 22000,
      priceItem: 45000,
      features: ["Dry clean included", "Dedicated handler", "Garansi kualitas"],
      highlight: false,
    },
  ],
  pricingRows: [],
  memberPackages: [],
  monthlyPackages: [],
  promos: [
    { title: "Diskon 25% Member Baru", code: "FRESH25", until: "30 Jun 2026" },
  ],
  testimonials: [],
  faqs: [],
  branches: [],
  cta: {
    eyebrow: "Mulai hari ini",
    title: "Siap bikin laundry lebih praktis?",
    description:
      "Daftar gratis, pesan dalam 2 menit, dan nikmati antar jemput plus tracking realtime.",
    backgroundImage:
      "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&q=80",
  },
};
